---
listen: localhost:8080

favicon:

relays:
- wss://relay.example1.com
- wss://relay.example2.com

nip_11:
  name: bostr2
  description: Nostr relay bouncer
  software: git+https://codeberg.org/Yonle/bostr2
  pubkey: 0000000000000000000000000000000000000000000000000000000000000000
  contact: unset
  supported_nips:
  - 1
  - 2
  - 9
  - 11
  - 12
  - 15
  - 16
  - 20
  - 22
  - 33
  - 40

# 0 is infinity
max_connections_per_ip: 3

# user agent to use on connecting to upstream
user_agent: bostr2 (https://codeberg.org/Yonle/bostr2) on wss://bostr.example.com - nostr relay proxy aggregator
